cbv/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.index,name='index'),
    path('cbv/',views.CBView.as_view()),
    path('cbv_index/',views.IndexView.as_view()),
    path('list/',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/',views.SchoolDetailView.as_view()),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view()),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),
]

posts/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('posts:list')

class Student(models.Model):
    name = models.CharField(max_length=100) 
    age = models.PositiveIntegerField()
    
    school = models.ForeignKey(School,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

posts/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,UpdateView,
                                DeleteView)
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import School

# Create your views here.
def index(request):
    return render(request,'posts/index.html')
    
class CBView(View):
    def get(self, request):
        return HttpResponse("실행완료!!!")
    
class IndexView(TemplateView):
    template_name = 'posts/cbv_index.html'
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['greeting'] = "안녕하세요!!"
        return context

class SchoolListView(ListView):
    model = School
    # schools = School.objects.all()
    template_name = 'posts/school_list.html'
    # return render(request,'posts/school_list.html',{'schools':schools})
    
class SchoolDetailView(DetailView):
    model = School
    template_name = 'posts/school_detail.html'

class SchoolCreateView(CreateView):
    model = School
    fields = ('name','location')
    
class SchoolUpdateView(UpdateView):
    model = School
    fields = ('name',)

class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy("posts:list")

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {%block body%}
    {%endblock%}
</body>
</html>

posts/templates/posts/cbv_index.html
{%extends 'posts/base.html'%}
{%block body%}
<h1>여기는 cbv_index입니다.</h1>
{{greeting}}
{%endblock%}

posts/templates/posts/index.html
{%extends 'posts/base.html'%}

{%block body%}
<h1>여기는 인덱스 입니다.</h1>
{%endblock%}

posts/templates/posts/school_confirm_delete.html
{%extends 'posts/base.html'%}

{%block body%}
    <form method="post">
        {%csrf_token%}
        <input type="submit"/>
    </form>
{%endblock%}

posts/templates/posts/school_detail.html
{%extends 'posts/base.html'%}

{%block body%}
<h1>hihi</h1>
    <h1>{{school.name}}</h1>
    <h1>{{school.location}}</h1>
{%endblock%}

posts/templates/posts/school_form.html
{%extends 'posts/base.html'%}

{%block body%}
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit">
    </form>
{%endblock%}

posts/templates/posts/school_list.html
{%extends 'posts/base.html'%}

{%block body%}
    {%for school in school_list%}
        <h1>{{school.name}}</h1>
        <a href="{%url 'posts:delete' pk=school.pk%}">삭제</a>
    {%endfor%}
{%endblock%}